class Solution {
public:
    // Monotonic stack code generated by gemini flash 3.5
    std::vector<int> findNextIndex(const std::vector<int>& arr, 
                               std::function<bool(int, int)> compare, 
                               bool reverseDirection = false) {
        int n = arr.size();
        std::vector<int> result(n, -1);
        std::stack<int> s;

        int start = reverseDirection ? 0 : n - 1;
        int end = reverseDirection ? n : -1;
        int step = reverseDirection ? 1 : -1;

        for (int i = start; i != end; i += step) {
            while (!s.empty() && !compare(arr[s.top()], arr[i])) {
                s.pop();
            }
            if (!s.empty()) {
                result[i] = s.top();
            }
            s.push(i);
        }

        return result;
    }
    std::vector<int> nextSmaller(const std::vector<int>& arr) {
        return findNextIndex(arr, std::less<int>(), false);
    }

    std::vector<int> nextGreater(const std::vector<int>& arr) {
        return findNextIndex(arr, std::greater<int>(), false);
    }

    std::vector<int> prevSmaller(const std::vector<int>& arr) {
        return findNextIndex(arr, std::less<int>(), true);
    }

    std::vector<int> prevGreater(const std::vector<int>& arr) {
        return findNextIndex(arr, std::greater<int>(), true);
    }

    long long maxTotalValue(vector<int>& nums, int k) {
        set<int> uniqueSet;
        vector<int> uniqueNums;
        unordered_map<int, vector<int>> mp;
        priority_queue<tuple<int, int, int>> pq;
        long long ans = 0;
        for (int i=0;i<nums.size();i++) {
            uniqueSet.insert(nums[i]);
            mp[nums[i]].push_back(i);
        }
        for (int i : uniqueSet) uniqueNums.push_back(i);
        for (int i=0;i<uniqueNums.size()-1;i++) {
            pq.push({uniqueNums[uniqueNums.size()-1]-uniqueNums[i], i, uniqueNums.size()-1});
        }
        vector<int> nextLesser = nextSmaller(nums), nextHigher = nextGreater(nums), 
                                 prevLesser = prevSmaller(nums), prevHigher = prevGreater(nums);

        while (k && !pq.empty()) {
            auto [value, minValueIdx, maxValueIdx] = pq.top(); pq.pop();
            int minValue = uniqueNums[minValueIdx], maxValue = uniqueNums[maxValueIdx];
            long long totalOcc = 0;

            for (int i=0;i<nums.size();i++) {
                int firstMinValueIdx = lower_bound(mp[minValue].begin(), mp[minValue].end(), i) - mp[minValue].begin();
                if (firstMinValueIdx == mp[minValue].size()) break;
                int firstMaxValueIdx = lower_bound(mp[maxValue].begin(), mp[maxValue].end(), i) - mp[maxValue].begin();
                if (firstMaxValueIdx == mp[maxValue].size()) break;

                int firstMinValue = mp[minValue][firstMinValueIdx], firstMaxValue = mp[maxValue][firstMaxValueIdx];
                int prevGreatestIdx = prevHigher[firstMaxValue], nextGreatestIdx = nextHigher[firstMaxValue];
                int prevSmallerIdx = prevLesser[firstMinValue], nextSmallerIdx = nextLesser[firstMinValue];
                if (nextGreatestIdx == -1) nextGreatestIdx = nums.size();
                if (nextSmallerIdx == -1) nextSmallerIdx = nums.size();
                if (nextGreatestIdx < firstMinValue) {
                    i = nextGreatestIdx;
                    continue;
                }
                if (nextSmallerIdx < firstMaxValue) {
                    i = nextSmallerIdx;
                    continue;
                }
                if (prevGreatestIdx >= i) {
                    i = prevGreatestIdx;
                    continue;
                }
                if (prevSmallerIdx >= i) {
                    i = prevSmallerIdx;
                    continue;
                }

                totalOcc += min(nextGreatestIdx, nextSmallerIdx) - max(mp[minValue][firstMinValueIdx], mp[maxValue][firstMaxValueIdx]);
            }
            totalOcc = min(totalOcc, (long long)k);
            ans += totalOcc * value;
            k -= totalOcc;
            if (maxValueIdx != minValueIdx+1) {
                pq.push({uniqueNums[maxValueIdx-1]-uniqueNums[minValueIdx], minValueIdx, maxValueIdx-1});
            }
        }
        return ans;
    }
};