#include <bits/stdc++.h>
#include <boost/multiprecision/cpp_int.hpp>

using namespace std;
using namespace boost::multiprecision;

typedef unsigned long long ull;
typedef long long ll;

int main()
{
    set<cpp_int> s;
    for (cpp_int a=2;a<=100;a++) {
        for (int b=2;b<=100;b++) {
            s.insert(pow(a, b));
        }
    }
    cout << "The number of distinct terms generated by a^b for 2<=a, b<=100 is " << s.size() << endl;
}